// Reads forge artifacts and the latest broadcast, then writes the typed ABIs and
// deployed addresses the frontend needs. Usage: node scripts-js/exportUrsset.mjs [chainId]
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const chainId = process.argv[2] || "46630";
const names = ["KYCRegistry", "MockIDR", "PropertyFactory", "PropertyToken", "RentDistributor", "PrimarySale", "Marketplace"];
// Only these are deployed once. Each listed property gets its own token, sale, distributor and marketplace
// from the factory, and the frontend reads those addresses from the factory at runtime.
const singletons = ["KYCRegistry", "MockIDR", "PropertyFactory"];

const abis = {};
for (const n of names) {
  abis[n] = JSON.parse(readFileSync(join(root, "out", `${n}.sol`, `${n}.json`), "utf8")).abi;
}

const zero = "0x0000000000000000000000000000000000000000";
const addresses = Object.fromEntries(singletons.map(n => [n, zero]));
let deployBlock = 0;
const runFile = join(root, "broadcast", "Deploy.s.sol", chainId, "run-latest.json");
if (existsSync(runFile)) {
  const run = JSON.parse(readFileSync(runFile, "utf8"));
  for (const tx of run.transactions) {
    if (tx.transactionType === "CREATE" && singletons.includes(tx.contractName)) addresses[tx.contractName] = tx.contractAddress;
  }
  const first = run.receipts?.[0]?.blockNumber;
  if (first) deployBlock = Number(BigInt(first));
} else {
  console.warn(`No broadcast for chain ${chainId}; writing zero addresses.`);
}

const out = join(root, "..", "nextjs", "lib", "generated", "ursset.ts");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by packages/foundry/scripts-js/exportUrsset.mjs. Do not edit by hand.\n` +
    `export const deployment = ${JSON.stringify({ chainId: Number(chainId), deployBlock, addresses }, null, 2)} as const;\n\n` +
    `export const abis = ${JSON.stringify(abis, null, 2)} as const;\n`,
);
console.log(`Wrote ${out}`);
console.log(addresses);
