// Major Indonesian cities and regencies, as "City, Province", for the property listing picker.
export const CITIES: string[] = [
  "Banda Aceh, Aceh",
  "Lhokseumawe, Aceh",
  "Medan, Sumatera Utara",
  "Binjai, Sumatera Utara",
  "Pematangsiantar, Sumatera Utara",
  "Padang, Sumatera Barat",
  "Bukittinggi, Sumatera Barat",
  "Pekanbaru, Riau",
  "Dumai, Riau",
  "Batam, Kepulauan Riau",
  "Tanjungpinang, Kepulauan Riau",
  "Jambi, Jambi",
  "Palembang, Sumatera Selatan",
  "Bengkulu, Bengkulu",
  "Bandar Lampung, Lampung",
  "Metro, Lampung",
  "Pangkalpinang, Kepulauan Bangka Belitung",
  "Jakarta Pusat, DKI Jakarta",
  "Jakarta Selatan, DKI Jakarta",
  "Jakarta Barat, DKI Jakarta",
  "Jakarta Timur, DKI Jakarta",
  "Jakarta Utara, DKI Jakarta",
  "Depok, Jawa Barat",
  "Bekasi, Jawa Barat",
  "Bogor, Jawa Barat",
  "Bandung, Jawa Barat",
  "Cimahi, Jawa Barat",
  "Cirebon, Jawa Barat",
  "Sukabumi, Jawa Barat",
  "Tasikmalaya, Jawa Barat",
  "Karawang, Jawa Barat",
  "Jatinangor (Sumedang), Jawa Barat",
  "Tangerang, Banten",
  "Tangerang Selatan, Banten",
  "Serang, Banten",
  "Cilegon, Banten",
  "Semarang, Jawa Tengah",
  "Surakarta (Solo), Jawa Tengah",
  "Salatiga, Jawa Tengah",
  "Magelang, Jawa Tengah",
  "Pekalongan, Jawa Tengah",
  "Tegal, Jawa Tengah",
  "Purwokerto (Banyumas), Jawa Tengah",
  "Kudus, Jawa Tengah",
  "Yogyakarta, DI Yogyakarta",
  "Sleman, DI Yogyakarta",
  "Bantul, DI Yogyakarta",
  "Surabaya, Jawa Timur",
  "Malang, Jawa Timur",
  "Batu, Jawa Timur",
  "Sidoarjo, Jawa Timur",
  "Gresik, Jawa Timur",
  "Kediri, Jawa Timur",
  "Jember, Jawa Timur",
  "Banyuwangi, Jawa Timur",
  "Madiun, Jawa Timur",
  "Denpasar, Bali",
  "Badung (Kuta, Canggu), Bali",
  "Gianyar (Ubud), Bali",
  "Singaraja (Buleleng), Bali",
  "Mataram, Nusa Tenggara Barat",
  "Kupang, Nusa Tenggara Timur",
  "Labuan Bajo (Manggarai Barat), Nusa Tenggara Timur",
  "Pontianak, Kalimantan Barat",
  "Singkawang, Kalimantan Barat",
  "Palangka Raya, Kalimantan Tengah",
  "Banjarmasin, Kalimantan Selatan",
  "Banjarbaru, Kalimantan Selatan",
  "Samarinda, Kalimantan Timur",
  "Balikpapan, Kalimantan Timur",
  "Bontang, Kalimantan Timur",
  "Nusantara (IKN), Kalimantan Timur",
  "Tarakan, Kalimantan Utara",
  "Manado, Sulawesi Utara",
  "Bitung, Sulawesi Utara",
  "Palu, Sulawesi Tengah",
  "Makassar, Sulawesi Selatan",
  "Parepare, Sulawesi Selatan",
  "Kendari, Sulawesi Tenggara",
  "Gorontalo, Gorontalo",
  "Mamuju, Sulawesi Barat",
  "Ambon, Maluku",
  "Ternate, Maluku Utara",
  "Jayapura, Papua",
  "Manokwari, Papua Barat",
  "Sorong, Papua Barat Daya",
  "Merauke, Papua Selatan",
];

/** Case-insensitive search that also matches the province. */
export function searchCities(query: string, limit = 8): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return CITIES.slice(0, limit);
  return CITIES.filter(c => c.toLowerCase().includes(q)).slice(0, limit);
}
